### ISSUE TITLE
Version 2.0 release

### ISSUE THREAD

**Issue by ThomasAkam** [pyControl/code#104]
@alustig3 - I woudl like to get the v2.0 release out soon so think we should stop working on new functionallity and get the last bits ready for the release.  Is there anything else functionallity wise you want to include in this release?  Otherwise I think the main things are updating the docs and checking the data import is working OK for the new data files.  Are you happy to do the bits of the docs relating to the changes that you've implemented, and I'll do the bits relating to mine?

**Comment by alustig3** [comment]
Moving forward with a release sounds good to me. Yes I will contribute documentation.

**Comment by alustig3** [comment]
When testing the `frame_trigger` class I am getting a bad checksum:

<img width="651" alt="image" src="https://github.com/pyControl/code/assets/8128628/a6a63355-5c8a-4239-bc17-f0c01ad0df5d">

I am running the following modified blinker.py task code:

```python
# A simple state machine which flashes the blue LED on the pyboard on and off.
# Does not require any hardware except micropython board.

from pyControl.utility import *
from devices import *

board = Breakout_1_2()

# Define hardware (normally done in seperate hardware definition file).

blue_LED = Digital_output("B4")
frame_trigger = Frame_trigger(pin=board.BNC_2, pulse_rate=60)  # Instantiate Frame_trigger on breakout board BNC_2


# States and events.

states = [
    "LED_on",
    "LED_off",
]

events = []

initial_state = "LED_off"

# State behaviour functions


def LED_on(event):
    if event == "entry":
        timed_goto_state("LED_off", 0.5 * second)
        blue_LED.on()
    elif event == "exit":
        blue_LED.off()


def LED_off(event):
    if event == "entry":
        timed_goto_state("LED_on", 0.5 * second)


# Run end behaviour


def run_end():  # Turn off hardware at end of run.
    blue_LED.off()
```

**Comment by ThomasAkam** [comment]
@alustig3 I think I'm finished updating the code and docs for the v2.0 release.  The `Frame_trigger` class appears to be working OK on my machine, I'm not sure what was causing the bad checksum but it seems to be fixed, could you check if you still get the error?

Is there anything else you think needs updating/fixing before the release?

**Comment by alustig3** [comment]
@ThomasAkam, I am still getting a bad checksum when using `Frame_trigger`. I've tried to debug a little bit on this branch: https://github.com/alustig3/pyControl/tree/frame_trigger_bad_checksum if you want to see if you can replicate. 
![Screenshot 2024-01-03 at 2 54 25 PM](https://github.com/pyControl/code/assets/8128628/636ce825-0131-4cd9-bd5e-86207136ad5c)

> Is there anything else you think needs updating/fixing before the release?

- I made some final documentation changes https://github.com/pyControl/docs/pull/25
- Is there any special instructions or warning that should be added to the [upgrade section](https://pycontrol.readthedocs.io/en/dev/#updating-pycontrol) of the docs with regards to going from v1 to v2?

**Comment by ThomasAkam** [comment]
@alustig3 I cannot reproduce the bad checksum error on my machine.

Looking at the output in the image you sent I think the problem must be to do with how the data bytes sent by the Frame_trigger are being converted into python arrays.  The content of those arrays should just be pulse numbers, so should start at 1 and increment by 1 each sample, as seen here where I print them to the log each time an analog chunk is recieved:

![image](https://github.com/pyControl/code/assets/4661184/35441d0b-1bfb-4f79-bf0e-551549292eca)

I suspect that the problem is that the byteorder is different in the data sent from the pyboard from that which the comptuer python is expecting when it converts the data to bytes.  This could either be because the byteorder different on Mac than windows, or because it is different on the pyboard D to the pyboard 1.1.  Can you test if modifying pycboard.py line 482 to explicitly specify the byte order fixes the problem:

```python
data = np.frombuffer(content_bytes[2:], dtype="<" + self.sm_info.analog_inputs[ID]["dtype"])
```

**Comment by alustig3** [comment]
@ThomasAkam the np.frombuffer line did not fix the problem.

I also modified my debug statement to be:
```python
bad_msg = f"Bad {data}\t{content_bytes[2]},{content_bytes[6]},{content_bytes[10]}\t\t{content_bytes}"
```

(updates here:https://github.com/alustig3/pyControl/commit/bc6ae88fc0ec0e8795cfe030a0606c9cfff08940)

I got the following output: 
![Screenshot 2024-01-04 at 10 00 42 AM](https://github.com/pyControl/code/assets/8128628/96ca1c07-7995-483a-94a0-cdd29911c4e7)

so it looks like the data is there, but packed with 3 zero bytes in between each value...

I think this is likely a Mac problem. I currently and debugging with a d-series board, but originally had the problem with a v1.1 board. I also downgraded the firmware to micropython v1.12 and it did not make a difference.

**Comment by ThomasAkam** [comment]
Hmmm, I think we expect there to be 3 zero bytes between each value becuase these are 4 byte integers and for numbers 1-255 only the last of the 4 bytes should be non-zero.  However it looks like first byte of the first sample  in each chunk is missing as there are only two zero bytes before the non-zero byte.  Does the Analog_input class work correctly?

**Comment by alustig3** [comment]
@ThomasAkam The problem is the datatype "l" is different on my mac. 

```python
import struct
for dtype in ("bhil"):
    print(f'{dtype} = {struct.calcsize(dtype)}')
```
gives
```
b = 1
h = 2
i = 4
l = 8
```

so on line 481 of pycboard
```python
data = array(self.sm_info.analog_inputs[ID]["dtype"], content_bytes[2:])
```
it was creating an array of 3 8-byte values instead of 6 4-byte values

I haven't had time to come up with a clean solution yet. I tried replacing line 301 of `hardware.py` with
```python
self.bytes_per_sample = struct.calcsize(data_type)
```
but it did not make a difference. Let me know what you think.

**Comment by ThomasAkam** [comment]
Thanks @alustig3.  I think a simple fix may be just to use `i` and `I` dtypes rather than `l` and `L` as they appear to be 4 byte length on pyboard windows and mac.  I've pushed a commit to the dev branch that does this, can you verify that it fixes the problem.

**Comment by alustig3** [comment]
@ThomasAkam that fixes the problem. Thanks!
