### ISSUE TITLE
Reader not backwards compatible with existing data files

### ISSUE THREAD

**Issue by bdudok** [pyControl/code#118]
Hi, 

 I have been using version 1.8.1 to save and read treadmill files. On a new install, existing data files are no longer correctly read.
In 1.8.1, I accessed some events in PyControl.code.tools.data_import.Session.print_lines
In the current version 2.0.1, there is no such attribute, instead there is "prints", but it's empty (on the same file).

Is it possible to keep the print_lines attribute accessible, or at least populate Session.prints from older data files?

Thanks,
Barna

**Comment by ThomasAkam** [comment]
Hi @bdudok, is the missing output from `print_variables` statements in the task code?

In the new [data_import.Session](https://github.com/pyControl/code/blob/a010c43a4173cca018c6ea24e5c4806a5964a7ae/tools/data_import.py#L20) class the output of `print_variables` statements is put into the `Session.variables_df` dataframe.  The rationale for this is that then the user does not have to do the parsing of the JSON output of print_variables themselves and has all the variable values in an easy to work with format.  

The output of standard `print` statements in task code should go into the `Session.prints` attribute as a list of namedtuples with fields `time` and `string`.

Let me know if this is working for your data files and also if it will be straightforward to adapt your analysis code to work with this.

**Comment by bdudok** [comment]
Hi @ThomasAkam,
 Thanks, the data is available from Session.variables_df, although the unit of time is in seconds while the unit of time in print_lines was in milliseconds (from the same input file). I'll test how everything integrates after I update the recorder.

**Comment by ThomasAkam** [comment]
You can control whether the time units are seconds or milliseconds using the time_unit argument when you instantiate the session class
