### ISSUE TITLE
Repo rename

### ISSUE THREAD

**Issue by AtMostafa** [pyControl/code#13]
The name of the repo should be changed to something more informative, e.g., "PyControlCode" or just "PyControl".
One advantage is that when it is cloned, the directory name immediately makes sense!

**Comment by ThomasAkam** [comment]
Hi AtMostafa,  thanks for your interest in pyControl.   

The current repo name works well the context of the broader project (https://github.com/pyControl) as there are additional repositories for hardware and documentation, and each has a sensible URL like https://github.com/pyControl/code.  I'm also reluctant to change the repo name becuase it will break links that users who have cloned the repo already have to it.

In the software I use for git (Sourcetree) it is straightforward to clone a repository into a folder with any name, so you can clone the repo into a folder called e.g. 'pyControl' irrespective of its name.
