### ISSUE TITLE
Display most recent print line in run task tab

### ISSUE THREAD

**Issue by lauralgrima** [pyControl/code#14]
Hi Thomas, would be great to include the display of the most recent print line (and perhaps the current state and last event) to the run task tab in the way that it's displayed in the run experiment tab. Thanks!

**Comment by ThomasAkam** [comment]
Thanks for the suggestion, I think this is a good idea and will implement it when I get time.

**Comment by ThomasAkam** [comment]
This is now implemented, thanks @alustig3!
