### ISSUE TITLE
mpremote

### ISSUE THREAD

**Issue by alustig3** [pyControl/code#19]
In the 1.16 release of Micropython there is a new command line tool for controlling devices : https://github.com/micropython/micropython/releases/tag/v1.16

The current pyControl serial connection seams to work well, so I'm not sure if this is useful, but may be worth taking a look at:
https://pypi.org/project/mpremote/

**Comment by ThomasAkam** [comment]
Hi Andy,

Thanks for sending that.  The tool does look interesting but as you say the current serial communcation is working well so I'm inclined not to change it.

T
