### ISSUE TITLE
Events plotting fails in pyQtGraph > 0.11.0 

### ISSUE THREAD

**Issue by alustig3** [pyControl/code#28]
If you upgrade pyqtgraph past version 0.11.0 then pyControl's events plot does not work.

It is a known issue for pyqtgraph. They no longer recommend using setPos to create the scrolling effect
https://github.com/pyqtgraph/pyqtgraph/issues/1916#issuecomment-884815091

recommended solution? https://github.com/pyqtgraph/pyqtgraph/issues/1798#issuecomment-850846858

As I a temporary solution, I've opened a pull request in the docs to explicitly pip install version 0.11.0 https://github.com/pyControl/docs/pull/5

**Comment by ThomasAkam** [comment]
I have just pushed a commit (67eea59586e8ad284d9ee3bca0a2994df1269827) to the dev branch that I think fixes this issue. @alustig3 could you test it on your machine to check the plots are behaving themselves.

**Comment by alustig3** [comment]
tested with pyqtgraph 0.12.3 and the issue is fixed. Thanks!
