### ISSUE TITLE
error loading framework

### ISSUE THREAD

**Issue by alustig3** [pyControl/code#41]
When testing 1.7.2 on our Windows computer I was unable to upload the framework to our pyboard

The loggging area of the run task tab shows:
> Micropython version: 1.17
> pyControl Framework: OK
> 
> Transfering pyControl framework to pyboard..
> Error: uncaught exception of type: <class 'AttributeError'>

The error log has the following:
> 2022-06-30 14:43:11,241 Traceback (most recent call last):
  File "C:\Users\karpo\Documents\pyControl\gui\dialogs.py", line 55, in load_framework
    self.board.load_framework()
  File "C:\Users\karpo\Documents\pyControl\com\pycboard.py", line 254, in load_framework
    self.transfer_folder(dirs['framework'], file_type='py', show_progress=True)
  File "C:\Users\karpo\Documents\pyControl\com\pycboard.py", line 241, in transfer_folder
    sys.stdout.flush()
AttributeError: 'NoneType' object has no attribute 'flush'

commenting out [line 241](https://github.com/pyControl/code/blob/9dc021250d879cd5ed75ef732754d2cf9ee99176/com/pycboard.py#L241)  fixes the problem and allows the framework to be loaded.

**Comment by ThomasAkam** [comment]
Thanks for spotting this.  I've just fixed it and update the release.
