### ISSUE TITLE
GitHub Discussions?

### ISSUE THREAD

**Issue by alustig3** [pyControl/code#47]
Should we consider having future pyControl questions and announcements on [GitHub Discussions](https://docs.github.com/en/discussions)? It has more features than Google Groups, and I think it would be preferable to have everything (code, issues, and questions) in one place.

### Some features
- good integration with linking to issues, pull requests, and repository code
- better posts and replies
    - easily view and scroll through entire thread
    - can have nested replies/discussions when replying to a post
    - can select an accepted answer
    - markdown editor with code blocks and syntax highlighting and other niceties
- organize discussions into categories
- create polls
- pin announcements
- can [convert issues into a discussion](https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion) (for instance, this "issue" could be moved into discussions)

### Other projects using discussions
- MicroPython recently made the move
    - https://forum.micropython.org/viewtopic.php?f=8&t=12971&sid=329429aeedb4a492901c29391b2c14e6
    - https://github.com/micropython/micropython/issues/8795

- Another neuroscience project, Auto-Pilot, successfully uses discussions
    - https://github.com/auto-pi-lot/autopilot/discussions

### To do if we make the change:
- [x] Make migration announcement post on Google Group
- [x] Change Google Group to read only
- [x] Add link to GitHub discussion in the Google Group description
- [x] Remove readthedocs links to Google Group and replace with links to GitHub discussions
- [x] Create and pin a welcome post to the GitHub discussion (like [this](https://github.com/orgs/micropython/discussions/9111)) that includes a link to the old Google Group
- [x] update pyControl's `Help->Forum` menu link
- [x] update "google group" links on open-phys [store](https://open-ephys.org/pycontrol/pycontrol) and [showcase page](https://open-ephys.org/pycontrol-showcase)
- [x] update  "forum" link on [labmaker page](https://www.labmaker.org/collections/neuroscience/products/pycontrol-mouse-behaviour-box_set_no1)

**Comment by ThomasAkam** [comment]
I think this is probably a good idea, it would be great to have markdown available for code blocks etc and the other features look useful.  I suggest we do this when we do the next release.   I'm currently working on a couple of updates I'd like to include in the next release, I hope to have these finished in the next week or two.

**Comment by alustig3** [comment]
should we proceed with this?

**Comment by ThomasAkam** [comment]
Yes, lets do this.  I've enabled discussion on the pyControl organisation.  

I would like anyone with a github account to be able to read and post to the forum, I think this is what the current permissions are set to but have not verified this yet.  

I have not yet created the wellcome post or made any of the changes to the docs etc that need to be done for the migration.  I'll work on this when I get time but the next few weeks are going to be busy.   @alustig3 If your able to do any of this it will move faster.

Also, do you think we should keep the common forum for pyControl and pyPhotometry?  This is quite convinent for me to manage but I guess it does not necessarily make sense as they are seperate projects with seperate Github organisations.

**Comment by alustig3** [comment]
I've updated forum links for the [docs](https://github.com/pyControl/code/pull/62)  and [code](https://github.com/pyControl/docs/pull/16)


> Also, do you think we should keep the common forum for pyControl and pyPhotometry? This is quite convinent for me to manage but I guess it does not necessarily make sense as they are seperate projects with seperate Github organisations.

it probably makes sense to have separate discussions that are tied to their GitHub organization

**Comment by alustig3** [comment]
@ThomasAkam the Open Ephys store page was correctly updated, but the [showcase page](https://open-ephys.org/pycontrol-showcase) still has a button/link to the google group

**Comment by ThomasAkam** [comment]
Thanks for letting me know, I've contacted OEPS to ask them to update the link.
