### ISSUE TITLE
pcx file reasoning

### ISSUE THREAD

**Issue by alustig3** [pyControl/code#58]
Is there a reason this json data is saved as a .pcx file and not a .json file?

https://github.com/pyControl/code/blob/5d046d8902aba1a96b7ef117eed97d677f8ce364/gui/configure_experiment_tab.py#L218-L221

**Comment by ThomasAkam** [comment]
No - it would make more sense to use a .json extension.  If we change it we should ensure backward compatibility with .pcx extension files.
