### ISSUE TITLE
Parallel setup configuration

### ISSUE THREAD

**Issue by alustig3** [pyControl/code#68]
In the setup tab, under "configure selected", it would be nice if the `load framework` and `load hardware definition` buttons could execute on all of the setups in parallel, similar to how tasks are loaded in parallel onto multiple setups when starting an experiment.

**Comment by ThomasAkam** [comment]
Yes, this would definitely be an improvement.   Also parallising the end of experiment process would be useful.

**Comment by ThomasAkam** [comment]
@alustig3 I've created a parallelisation branch in which I've implemented parallel operations on multiple boards for the setups tab, and also parallelised the actions done at the end of running an experiment (reading variables etc).  I've tried to test all the functionallity but it is possible there are still some bugs.  Could you give it a try and if your happy with it I'll merge it into the dev branch.

**Comment by alustig3** [comment]
thanks for doing this, the speed improvements are great!

I came across one bug. The `Variables` button is not working for my experiment. Below is a video demonstrating that the variable dialog works as expected when using the Run task tab, but it fails to open when using the Experiments tab. My terminal shows the error message:
`QObject::setParent: Cannot set parent, new parent is in a different thread`
The subjectbox start/stop buttons work as expected.

https://user-images.githubusercontent.com/8128628/225121297-df84b3cb-0202-42d2-894b-b06110d043e4.mp4

<br>

another minor "bug", that already existed before your changes, is that if you go to load the hardware definition, if you cancel the dialog, it still tries to load the hardware definitions and prints "Hardware definition file not found." to the log. 
A fix to this would be to add
```python
if hwd_path != "":
    self.accept()
    self.board.load_hardware_definition(hwd_path)
```
to https://github.com/pyControl/code/blob/f5d95272cbc375b321a99cfce6ca6bc1a032e0e6/gui/dialogs.py#L59

and 
```python
if self.hwd_path != "":
    self.print_to_log('\nLoading hardware definition')
    parallel_call('load_hardware_definition', self.get_selected_setups())
```
to https://github.com/pyControl/code/blob/f5d95272cbc375b321a99cfce6ca6bc1a032e0e6/gui/setups_tab.py#L188

**Comment by ThomasAkam** [comment]
These bugs should now be fixed in ab408dd37cf97d5d2f7879e96e5875562e305674, can you take a quick look and let me know if you happy to merge this.

**Comment by alustig3** [comment]
the variables button bug is fixed 👍 

would it be possible to add some indication that the parallel calls are working/pyControl is processing the command? right now when in the setups tab when I click `Load framework` or `Load hardware definition` it seemingly does nothing, then after some time, the log data is printed all at once. 

also I am seeing some weird behavior (although it is sort of an edge case and not critical). In setups tab If I load hardware, then cancel, then switch tabs, then switch back to setups tab, there is printed text as if `setup.start_delayed_print()` was called. example video below:

https://user-images.githubusercontent.com/8128628/225156694-ab3251d9-d2c2-4575-938f-2533673b98a8.mp4

**Comment by ThomasAkam** [comment]
I just pushed a commit which fixes the issue where output was printed to the log on changing tabs.  

> would it be possible to add some indication that the parallel calls are working/pyControl is processing the command?

When you press a button to start an operation, you should immediately see a line in the log which says e.g. 'Loading framework...' is that not happening on Mac?

**Comment by alustig3** [comment]
> I just pushed a commit which fixes the issue where output was printed to the log on changing tabs.

thanks, the fix worked for me.

> When you press a button to start an operation, you should immediately see a line in the log which says e.g. 'Loading framework...'

👍  cool, that's what I wanted, good to know an indication of sorts is there. yes, interestingly it is not working on my Mac.  

https://user-images.githubusercontent.com/8128628/225404200-b7f1c344-9156-4831-97c2-4d8cbeb5c1fe.mp4

When the delay is long enough, a Mac busy "spinning wheel" eventually appears, so it isn't terrible. I've tried adding `time.sleep(.1)` calls after the `self.print_to_log()` calls and it doesn't fix the problem. I realize it will be hard for you to fix if you can't replicate it, so don't let this hold up the merge. If later on find a solution I will let you know.

**Comment by ThomasAkam** [comment]
@alustig3 could you try modifying the function:

https://github.com/pyControl/code/blob/1723f84988dbb0644a060df98cb73fc74a6bcea1/gui/setups_tab.py#L172-L174

to read:

```python
    def load_framework(self):
        self.print_to_log('Loading framework...\n')
        self.GUI_main.app.processEvents()
        parallel_call('load_framework', self.get_selected_setups())
```

and let me know if that causes the `Loading framework...` message to appear in the log when the button is pressed.

**Comment by alustig3** [comment]
that did not fix it

**Comment by ThomasAkam** [comment]
In that case I don't know what the solution might be.  I'll merge this into the dev branch now.
